### PR TITLE
Fix the font family name

### PR DESCRIPTION
**Pull request by toolmantim**
Currently all the SVG graphics use the wrong font-family name, `Stem-Regular`:

font-family-before

This updates all the font-family references to be `Stem Text`:

font-family-after

### CODE REVIEW

**Comment by palkan** [comment]
Good catch! Thanks!

**Comment by toolmantim** [comment]
I noticed the animations aren't working anymore. I might have botched something. You might want to revert and I'll check it out again.

**Comment by toolmantim** [comment]
(I should have tested locally)

**Comment by palkan** [comment]
No-no, that's my fault, don't worry) I'll fix it soon

**Comment by toolmantim** [comment]
Phew! Ok, cool 👍

**Pull request merged**
